### ISSUE TITLE
failing GC assertion when array is modified in the block passed to #each

### ISSUE THREAD

**Issue by cremno** [mruby/mruby#2825]
From https://github.com/mruby/mruby/issues/2769#issuecomment-107824354, reduced to:
```ruby
a1 = [0, 1] # at least 2 elems are needed (with only 1 it iterates a1 only once and not forever)
a2 = []

a1.each do |e|
  a1 << []  # or any other non-immediate
  a2 << e  # works as expected if commented out
end
```

https://github.com/mruby/mruby/blob/630c2c5853b976c3ca753d9713590b3e972621b8/src/gc.c#L1100

**Comment by tsahara** [comment]
At the time mruby dies:

1. `e` is `[]` appended to `a1` 2 iterations before (I call it X).
2. `a1` has a reference to X because it was appended to `a1` 2 iterations before.
3. `a1` is grey.
4. `a2` is black.
5. `is_dead(mrb, value)` is true because X is *previous-white*.
6. That's why `mrb_assert(!is_dead(mrb, value) && !is_dead(mrb, obj));` fails.

But I don't know why the assertion checks that `value` is *current-white*?
Removing the assertion, the problem disappears and all unittests pass.

**Comment by tsahara** [comment]
>But I don't know why the assertion checks that value is current-white?

Anyone knows?

**Comment by matz** [comment]
`is_dead()` is not valid during mark phase.
