### ISSUE TITLE
mrb_string_value_cstr crashes if not given a string

### ISSUE THREAD

**Issue by jbreeden** [mruby/mruby#2847]
`mrb_string_value_cstr` does horrible things if given an argument that isn't actually a string (well, it tends to crash, anyway). That's all fine and well, since in C you should know what you're doing with your pointers. However, `mrb_string_value_ptr` avoids this by calling `mrb_str_to_str` on its argument. I'm just wondering if there's a reason that they behave differently. (Until now, I thought the _cstr version just stopped at the first null character, and _ptr was more suited to arbitrary char buffers. It wasn't clear to me that one is more type sensitive.)

I didn't see any issues/discussions on this yet. Maybe I'm the only one that's confused... O_o

**Comment by cremno** [comment]
You should create a PR since I agree that `mrb_str_to_str()` has to be called. I think most mruby users call `mrb_str_to_cstr()` instead which is very strict (only `MRB_TT_STRING`) and (or but?) creates a copy. Also this function is only used once in mruby and there it's preceded by a check. That's probably why nobody did find this bug before.

However there's something else: `mrb_str_to_str()` does much more than `rb_str_to_str()`. Is this intended, @matz?

https://github.com/mruby/mruby/blob/e344c6ab6d7b3d6a8ffcec6f7f96aeba6c5fdeda/src/string.c#L628-L641
https://github.com/ruby/ruby/blob/a02a3f46496210ca401fd74585993c8754cbe91c/string.c#L1087-L1091

**Comment by jbreeden** [comment]
Sounds good. I'm heading to work, I'll make the PR when I get back.
