### ISSUE TITLE
Future of the build system

### ISSUE THREAD

**Issue by bovi** [mruby/mruby#3113]
Hi *,

I saw that someone is building [an external build system](https://github.com/zzak/mruby-build) for mruby. Based on @matz https://github.com/mruby/mruby/issues/3094#issuecomment-178897893 it seems to me that there were some offline discussions about such a potential build system. For me this seems to might have a potential larger impact, as the new design suggests to integrate itself strongly in standard rake (might be incompatible to minirake) and will depend on a CRuby Rubygem. Even if I can see some of the benefits, several of my projects strongly depend on the current design of the mruby building system and its current feature-set. So I would like to know if we have to prepare ourselves that the build system might be changed dramatically in the short-term? 

/daniel

**Comment by matz** [comment]
You have to ask @zzak who is working on experimenting new build system. Although I asked him working on it, I haven't touch with its design.

**Comment by bovi** [comment]
@matz ok I see. In general I would like to know if from your side it would be acceptable to remove the build system out of the main repository into a CRuby Gem?

**Comment by zzak** [comment]
Hello @bovi!

Thank you for your interest in the future of mruby's build system. I hoped to talk to you at some point about my plans for the project, so I'm glad you made this ticket :)

First to answer your concerns, I plan to keep the build system compatible with existing versions of mruby and procedures for compiling mruby. That includes minirake, for now.

>  the new design suggests to integrate itself strongly in standard rake (might be incompatible to minirake) and will depend on a CRuby Rubygem.

Let me address the first concern: our first step is to extract the existing build system, which is already built using Rake. So in order to extract this system and refactor it into a gem we needed to use Rake's TaskLib DSL, otherwise we're stuck passing long path names to `load` to get these tasks to load in the proper order. See [`MRuby::Rules`](https://github.com/zzak/mruby-build/blob/master/lib/mruby-build/rules.rb).

Secondly, the reasons we're using a RubyGem is to be able to maintain and refactor the build system outside of the mruby release cycle. One advantage of this is being able to build multiple versions of mruby, or even just certain parts of the build system at a time (instead of the current compile-the-world style).

Once we have something shipable, the goal is to vendor the latest version of `mruby-build` gem in the source of mruby to be released (just like RubyGems is vendored with MRI).

With regards to your concerns re: `minirake`, I think it should work, but we might need to implement some `TaskLib` shim to support the new system. I'm curious what other requirements you might have, and would appreciate any more feedback on the new system you have!

I realize you've worked really hard on the current system, and helped pioneer the foundations of mruby, so I'd really like your help with this <3 <3 <3 <3

Thank you!!!

**Comment by bovi** [comment]
Hi @zzak,

thanks for introducing your ideas. Don't get me wrong, I'm all for permanent change and think your ideas are very reasonable and I would be glad to contribute to this task. I just wanted to have a clear view in which direction this might move. I'm all willing to change the pre-reqs. of my projects as long as we don't blow up the core of mruby unreasonable big. Adding standard rake and Rubygems as a pre-condition to compile mruby seems to be not the biggest pain-point. But I'm a bit worried about the cross compling features (which are very important to my work). The dependencies are to a certain extend kind of complex at the moment, it would be probably benefitial to other users to simplify them but of course without breaking them ;-)

So as I understand the tasks are currently:
  - extract mruby rake tasks into gem
  - use standard rake features to simplify rake tasks
  - add new features to the build system

Sounds exciting!

Regards
Daniel

**Comment by beoran** [comment]
How is this coming along?
