### ISSUE TITLE
1.3.0 Changes

### ISSUE THREAD

**Issue by zzak** [mruby/mruby#3140]
Let's use this ticket as a catch-all for features/changes in the upcoming release of MRuby.

It will help me, or whoever, writing the release announcement ;)

If you see a commit or pull request get merged which can be considered a feature, just comment a reference to this ticket!

Thank you!!

**Comment by jmhmccr** [comment]
Looked through commits for some end user visible changes (was curious myself) and the below stood out as summarizable takeaways.

Enumerable#take, #cycle and #first improvements #3293 #3271 #3246

Hash#[] should always call #default #3272
Copy default_proc by Hash#dup #3328

Multiple C++ and Visual Studio compatibility improvements.

**Comment by matz** [comment]
@jmhmccr Thank you for aggregating entry candidates here. It will help to edit the change entries later.

**Comment by felixjones** [comment]
Any changes to the C API should probably be included.

I'd like to see the fixes to the supplied Android NDK toolchain mentioned as I imagine mobile platforms to be a good point of promotion for mruby's potential application. Of course, I am biased on this one.

**Comment by dabroz** [comment]
#3251 is also a new C API feature.

**Comment by beoran** [comment]
Sorry if this the wrong place to ask, but around what time could we expect 1.3.0 to come out? I 'd like to know for a certain project where I can only use "official" release versions. Is anything still blocking the next release?

**Comment by matz** [comment]
Ah, we still don't know. I wanted to implement keyword arguments before 1.3 but have been busy fixing other bugs. Options are
* wait until keyword arguments implementation
* postpone keyword arguments to 1.4. Release it after fixing several remaining bugs

If we choose the latter, we can release it by April/May.

**Comment by dabroz** [comment]
I vote for the latter - 1.3 would be a big step forward even without keyword arguments.

BTW - since we are using GitHub to manage development, we could also benefit from milestones and labels. It would be clear what is the scope of each release.

**Comment by beoran** [comment]
I would also appreciate it if we could have a 1.3 release this spring. It's
been a long time since 1.2 and I eagerly await all the fixes already in
development now. For me, keyword arguments can wait until 1.4. The Ruby ISO
standard doesn't mention those anyway so I am not able to use those for my
work project.

**Comment by felixjones** [comment]
As much as I'd love key-word arguments to make an appearance, the version number is not going to speed that up.

It seems a number of people are relying on a clear cut version that will hard define that no active changes will occur, so with this knowledge, perhaps a named 1.3 release is required.

I think it would be best is to resolve the remaining security issues before preparing a 1.3 final.

**Comment by matz** [comment]
OK, I choose the latter. The goal for 1.3 release is the end of March.

**Comment by beoran** [comment]
I guess 1.3 is slightly delayed? Could you please give an estimate of the new ETA?

**Comment by matz** [comment]
I still need more time to address issues reported from Shopify bounty. If they won't submit more errors, new EST will be mid-May.

**Comment by beoran** [comment]
Thank you for the update and for your efforts. Since these are important
bug fixes, I think it is worth waiting for them.

**Comment by matz** [comment]
The mruby 1.3 has been frozen as of June 20th, 2017. It will be released in early July.

**Comment by matz** [comment]
Stats (from 2015-11-17 to 2017-06-20):
* 1175 commits
* 248 issues fixed
* 262 pull requests merged

**Comment by zzak** [comment]
https://github.com/mruby/mruby.github.io/pull/52

Could use some help writing the change notes! :bow:

**Comment by matz** [comment]
# mruby1.3 release note

mruby 1.3 was released on 2017-07-04.

# Highlights of the changes

## The safe navigation operator (`&.`)

mruby1.3 now supports the safe navigation operator (`&.`)
to help handle `nil` value returned from methods. It's Ruby2.3 feature.

By using the safe navigation operator, you can simply write

  ```ruby
  account&.owner&.address
  ```

Instead of writing

  ```ruby
  account && account.owner && account.owner.address
  ```

Or (with ActiveSupport)

  ```ruby
  account.try(:owner).try(:address)
  ```

## `Array#dig`, `Hash#dig`

`#dig` is a method to retrieve a value from JSON-like nested Array/Hash structures.
It's Ruby2.3 feature.

For example:

  ```ruby
  params.dig(:account, :owner, :address)
  ```

Instead of

 ```ruby
  account = params[:account]
  owner = account[:owner]
  owner[:address]
  ```
## `Object#freeze`

You can "freeze" an object by using `Object#freeze`.
Frozen objects cannot be modified.

## `Kernel#caller`

You can retrieve call frame information by using `Kernel#caller`.

# Stats

* 1177 commits
* 248 issues fixed
* 262 pull requests merged

# Remaining Bugs

After the code-freeze of 1.3 release, following issues are filed and fixed in the master branch.

* #3711
* #3712
* #3714
* #3715
* #3716
* #3717
* #3719
* #3720
* #3721
* #3722
* #3723
* #3724

The following issues are not yet fixed as of 2017-07-04.

* #2720
* #3629
* #3710

**Comment by beoran** [comment]
Finally a new stable release for mruby. :) Thanks to you, matz, and
everyone else involved for all their efforts!
