### ISSUE TITLE
Simple Rust build script.

### ISSUE THREAD

**Issue by dragostis** [mruby/mruby#3143]
I've written a [Rust binding for mruby](https://github.com/anima-engine/mrusty), but it currently requires a compiled `libmruby.a` library.

I was wondering if writing a build script in Rust was complicated and if there was anyone willing to help me with this. I'm considering compiling YACC files to C, then offering all the C files as a package on GitHub. Then, by using Rust's Cargo [custom build scripts](http://doc.crates.io/build-script.html#case-study-building-some-native-code) it could generate the `libmruby.a` dependency on any platform with a C compiler.

What do you think about the approach? The way I currently see it is that this build script would build mruby, the default gems and add everything to the `.a` file which Rust knows how to depend upon.

**Comment by steveklabnik** [comment]
There will be a Rust RFC coming any day now which will make it much easier to integrate stuff like YACC into a Rust crate. I haven't toyed with mruby much lately, but you might be able to get away with just it?

**Comment by dragostis** [comment]
@steveklabnik Offering compiled YACC files seems sufficiently reasonable to me. This would reduce the number of dependencies to just `cc`, so anyone would be able to compile mrusty with cargo and their default C compiler.

**Comment by bovi** [comment]
are u having something similar to rake or cmake in Rust?

**Comment by dragostis** [comment]
@bovi Cargo, the default build tool of Rust has custom [build scripts](http://doc.crates.io/build-script.html#case-study-building-some-native-code) that can be coded in Rust. That example uses a crate (Rust gem equivalent) inside of the build script to make compiling C files easy on pretty much any platform.

**Comment by bovi** [comment]
just had a look at these build scripts. I think it should be straight forward to port a static build system to Rust. Yet I would suggest you to pre-compile the ruby based std-lib so that you do not need to pre-built mrbc to bootstrap mruby. if you have build system specific questions just drop a message here.

**Comment by dragostis** [comment]
Pre-compiling them sounds like a good idea.

About porting the build system, what do you think should be essential to porting minirake to Rust? Should I go for a thorough port or not? I'm not very accustomed to writing native build scripts. :stuck_out_tongue:

**Comment by bovi** [comment]
Oh, if I would be you I would skip minirake completely, the complexity grow quite a bit due to the cross compilation rules we introduced before, which you do not need at all. Have a look at this document I wrote some time ago: https://github.com/mruby/mruby/blob/master/doc/guides/compile.md 
It shows under build process what essential parts exist in mruby and how the build system builds them step by step. A first step would be to ignore the mrbgems and just build the core from "src/" even skipping the compiler which is a mrbgem itself. After you are able to build this and you can instantiate a mrb instance in Rust you can go forward and extract the gems you like to put into your "crate" one by one. Maybe your cargo tool has also some kind of file dependencies. Somthing in the direction: to build this file you need to compile -> these files. Some feature like that would be quite handy for build scripts in general but it of course also works procedual, just a bit harder to understand.

**Comment by dragostis** [comment]
@bovi Got it. Sounds really good and this should be really simple to implement.

**Comment by dragostis** [comment]
@bovi How can I use `mrbc` to compile multiple .rb files to a .c file?
