### ISSUE TITLE
Memory corruption during codegen on a rogue break statement

### ISSUE THREAD

**Issue by sgnr** [mruby/mruby#3152]
Hi!

The following code causes a memory corruption
```ruby
def d
  begin
    break
  end
  rescue
end
```
with the following message
```
codegen error:(mirb):6: unexpected break
codegen error
mirb(24790,0x7fff73113000) malloc: *** error for object 0x7fb0aad019c0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

I can reproduce it with both my custom configuration and the default `build_config.rb`.

**Comment by cremno** [comment]
https://github.com/mruby/mruby/blob/b4e188981347de04e781aecbced141bee544688a/mrbgems/mruby-compiler/core/codegen.c#L2804

This has to be a runtime error (`raise_error()`+`return` instead of `codegen_error()`). Not sure why though. What's the reason such errors can't be raised at compile time like in CRuby, @matz? A mruby limitation?

**Comment by matz** [comment]
@cremno it's not impossible at all, just I was too lazy to maintain static scope information for local jumps.
