### ISSUE TITLE
Crash when eval "Fiber.yield"

### ISSUE THREAD

**Issue by i110** [mruby/mruby#3415]
The following code causes a crash with a SEGV.

```ruby
Fiber.new { eval "Fiber.yield" }.resume
```

Is this possible in mruby?

**Comment by kazuho** [comment]
For context, this is a bug that we ran into while looking for a way to load and evaluate a code within a fiber.

In H2O, we would like to evaluate mruby code that defines a Rack handler within a fiber, so that when a blocking operation is triggered within the evaluation `Fiber.yield` could be used to transfer that operation into C code.

Essentially, we would like to allow users to write something like the snippet below, which will be evaluated within a fiber (note: `join` methods calls `Fiber.yield` to delegate network operations to the main fiber).

```ruby
# cache the response from http://upstream, and use it for every request
cached_resp = http_request("http://upstream/").join[2].join
Proc.new do |env|
    [200, [], [cached_resp]]
end
```

**Comment by matz** [comment]
It's not possible, mruby's fiber cannot cross C function boundaries, although causing SEGV is a bug.

**Comment by kazuho** [comment]
@matz Thank you for the clarification. The reasoning sounds totally reasonable that you cannot call `yield` from an `eval`-ed script running in a fiber due to C function boundaries.

OTOH, may I ask if you have any idea that we could solve the issue? As stated in https://github.com/mruby/mruby/issues/3415#issuecomment-275016287 what we want to do is to evaluate user-specified script in a child fiber. We are more than happy to write such solution in C.

**Comment by i110** [comment]
Another question: Are there standard ways to generate `Proc`'s instance from mruby source code?
(sorry for changing the topic from this issue)

We found that we can address the issue described in https://github.com/mruby/mruby/issues/3415#issuecomment-275016287 by passing the compiled code to some preparing method as a proc. Like the following, `prepare_app` method call that compiled proc in a fiber because compiled_proc may call `Fiber.yield`.
```ruby
def prepare_app(compiled_proc)
  Fiber.new do
      compiled_proc.call
  end.resume
end
```
But as far as I see the mruby API, there seem to

**Comment by i110** [comment]
Sorry, I mistakenly closed this issue

**Comment by matz** [comment]
48e0bbb allows you to call `Fiber.yield` from within `eval()`.
