### ISSUE TITLE
BasicObject's instance methods

### ISSUE THREAD

**Issue by catsidhe** [mruby/mruby#3417]
```
BasicObject.instance_methods
```
Ruby:
```
[:!, :==, :!=, :__send__, :equal?, :instance_eval, :instance_exec, :__id__]
```
mruby:
```
[:method_missing, :initialize, :!]
```
Is there a reason for this difference? In particular, ```#__send__``` can be pretty useful.

One workaround is to use ```eval("obj.#{method_name}(*args, &block)")```, but it's obviously a poor solution.

Another potential workaround:
```
Kernel.instance_method(:send).bind(obj).call(:method_name)
```
crashes with:
```
Segmentation fault: 11
```
(both Object and BasicObject)

**Comment by ksss** [comment]
It's interesting.
I don't know why `BasicObject#__send__` is nothing.

But,

> Kernel.instance_method(:send).bind(obj).call(:method_name)

It might be [mruby-method](https://github.com/ksss/mruby-method)'s problem.
I'll check it later.

**Comment by matz** [comment]
I made `BasicObject` compatible with CRuby, with two exceptions:
* `binding` is not implemented for mruby
* `instance_exec` which is implemented in `mruby-object-ext` gem and moving it to `BasicObject` is difficult. I don't think it's worth the price of implementation complexity.
The SEGV issue is very interesting, but since it is a separate issue (probably) in `mruby-method`, it should be treated independently.

**Comment by ksss** [comment]
ksss/mruby-method size solved at https://github.com/mruby/mruby/commit/8a15abdac2d05d70018f950d428abb0957d7ebd0
Thanks
