### ISSUE TITLE
statically compiled mruby binaries for different platforms?

### ISSUE THREAD

**Issue by timuckun** [mruby/mruby#3707]
Are there statically compiled binaries of the mruby interpreter for Linux, Mac, ARM etc? Ideally I would like to be able to upload a directory of .rb files and a binary to a device or a server and be able to execute the scripts without having to compile anything on the device itself. 

Thanks.

**Comment by matz** [comment]
1. compile you .rb files into a C file by mrbc, e.g. `mrbc -Binit_yourlib -o mrblib.c *.rb`
2. your application needs to call `init_yourlib(mrb)` after `mrb_open()`.
3. compile your application with the generated C file and link with libmruby.a
4. you may need to specify static link option to the linker.

The other option is creating a binary mrbgem. See `mrbgems/mruby-bin-mirb` for example.

**Comment by timuckun** [comment]
The problem is that I want some flexibility in the scripts I want to run. I might even want to download or rsync the scripts from another server. What I want is a statically compiled interpreter which then can run the scripts

For example red language offers prebuilt binaries which are very small and can be downloaded as a single executable.  http://www.red-lang.org/p/download.html

**Comment by matz** [comment]
I am not sure whether I understand your demand. The standard `mruby` command is a compiled interpreter. You can compile it statically with a slight modification of linker option. You can load scripts into your interpreter using `mruby-require` mrbgem. Of course, you have to take care of security risk.

https://github.com/mattn/mruby-require

**Comment by timuckun** [comment]
I am asking if there are statically precompiled mruby interpreters for different architectures. The obvious ones being ARM (raspberry pi, getchip etc), Linux, MacOSX etc. Ideally there would be just one file I can upload to a small device along with some ruby scripts and then run those scripts on that machine without having build-essentials or the equivalent being on the machine. 

Sorry if I am not making myself clear.

**Comment by shevegen** [comment]
I am also not entirely sure what you mean timuckun :) - but I guess you are asking whether you can make a statically compiled, standalone variant of mruby that will work without any external dependency e. g. no .so, and I think that is possible (although I have not tried myself yet). I am also interested in a statically compiled mruby because of it being less "failure-prone", e. g. when I modify some other libraries or components and temporarily break something. This is why I usually also have a statically compiled variant of busybox, which is nice; and with ruby then also working, in this case mruby, my ruby scripts should also function.

> Ideally there would be just one file I can upload to a small device along with some ruby scripts 

To your last question, actually, it should be possible to have someone be able to offer such downloads of a statically compiled mruby available right? For all platforms, linux-flavor, osx, windows. 

I had a look at lua and they seem to provide some binaries including windows:

    http://sourceforge.net/projects/luabinaries/files/5.3.3/Tools%20Executables/lua-5.3.3_Linux319_64_bin.tar.gz

I downloaded the last, to have a look whether it is shared or not, via ldd:

  ldd lua53

        not a dynamic executable

So I assume that is statically compiled. I believe that github even allows some download
variants e. g. where you could pick a different variant to download, if this is provided (I am not sure if matz has enough time to do so right now but perhaps in the coming years ... or someone figures out a simple way how to do this on github :D). Once someone has a compiled variant that works on e. g. ARM, it could be re-distributed from the official homepage too (may be easier; or you could perhaps also add some documentation to describe the process as-is but I guess whoever does that, it may be good if the whole process is described in some file, like a .md file, and if you then write a PR issue including the step-by-step, matz will perhaps add this to the documentation part of mruby).

**Comment by matz** [comment]
The primary target of mruby is embedded environment on a wide range of platforms and OSes. We don't have any plan to provide precompiled binary of mruby for specific platforms.

**Comment by r-obert** [comment]
sometime it's nice when there's binary packages and a checksum that can be used to verify its contents for automation scripts. RVM does something similar for Ruby but i don't think the binaries are static.
