### ISSUE TITLE
#sprintf integer with min width adds additional spaces

### ISSUE THREAD

**Issue by christopheraue** [mruby/mruby#3736]
```ruby
# file: sprintf.rb

(1..10).each do |i|
  puts sprintf "%8d behind", 10**i
end
```

Ruby behaves as expected:
```
$ ruby sprintf.rb
      10 behind
     100 behind
    1000 behind
   10000 behind
  100000 behind
 1000000 behind
10000000 behind
100000000 behind
1000000000 behind
10000000000 behind
```

mruby decides it needs more space:
```
$ mruby sprintf.rb
      10       behind
     100      behind
    1000     behind
   10000    behind
  100000   behind
 1000000  behind
10000000 behind
100000000 behind
1000000000 behind
```

**Comment by shevegen** [comment]
Looks as if mruby attempts to create a Haiku/poem layout. Reminds me of the "xmas ascii art" that used to be on the ruby mailing list years ago by some ruby hacker who loved doing that. :)

**Comment by take-cheeze** [comment]
Just sharing workaround for people using 1.3.0:
1.  Copy `mrbgems/mruby-sprintf/` from latest mruby master branch to your project directory.
2. Add `gem 'PATH_TO_MRUBY_SPRINTF'` to your `build_config.rb` so that core mruby-sprintf won't be used.

Having things managed with mrbgems are great.
BTW `mruby-time-strftime`'s test fails due to this bug.
