### ISSUE TITLE
default to MRB_INT64

### ISSUE THREAD

**Issue by yannick** [mruby/mruby#3800]
i would have expected to be able to use 64bit integers on a 64bit system. 
is there any reason to not enable `MRB_INT64` in a similar way than `MRB_64BIT` is enabled?

**Comment by matz** [comment]
`MRB_NAN_BOXING` requires `MRB_INT32` even on 64bit systems.
But maybe there's something we can do.

**Comment by yannick** [comment]
would be nice if its possible and if not what are the consequences of enabling it in a  project that uses mruby.

i would also be interested to understanding why MRB_NAN_BOXING (which is also disabled by default?) is connected to MRB_INT32.

discussion was sparked here: https://github.com/h2o/h2o/issues/1394 
is i found it odd that unix timestamp ended up as floats.

**Comment by matz** [comment]
1. `MRB_NAN_BOXING` means Ruby value (both reference and immediate like integers and symbols) are packed in double float value. Because of the data size, integers must be smaller than double floats (64bits).
2. UNIX timestamps are represented by float values as CRruby does. In most cases, float values are big enough to contain timestamp data and more handy to process (as numbers).

**Comment by matz** [comment]
I updated the configuration condition. If you don't specify any specific integer size, and not use `MRB_NAN_BOXING`, `MRB_INT64` will be used on 64bit architectures.

**Comment by yannick** [comment]
awesome, thank you!
