### ISSUE TITLE
Why I can't use unicode characters in ruby class name or module?

### ISSUE THREAD

**Issue by mikolaj24** [mruby/mruby#3910]
```
#!/usr/bin/env ruby
# encoding: utf-8

module Żółć
end

class Żółte
end

```
I can use unicode char in definition of functions

**Comment by matz** [comment]
To determine cases for non ASCII characters, we need to embed huge Unicode case information table. I don't think it's sufficient for embeddable implementation of Ruby language.

**Comment by and09** [comment]
not exactly.
finction inside object CAN using unicode. Why class name not?

**Comment by dkasak** [comment]
I suppose matz mentioned cases due to the restriction that Ruby class names must be constants, whose names have to begin with an uppercase letter. Therefore, mruby would have to contain case information to determine which Unicode symbols are uppercase. It works for functions because there is no such restriction on function names.

**Comment by matz** [comment]
That's correct. You can use Unicode characters in class names if you use ASCII character for the first letter. CRuby followed same rule until 2.3

**Comment by mikolaj24** [comment]
For arch:
This working, thanks.

#!/usr/bin/env ruby
# encoding: utf-8

module MŻółć
end

class MŻółte
end
