### ISSUE TITLE
warning in ruby

### ISSUE THREAD

**Issue by letarg0** [mruby/mruby#3980]
I get this in -pedantic mode in ruby. This warning apear in mruby?

```
/usr/include/ruby-2.3.0/ruby/ruby.h:841:45: warning: enumerator value for ‘RUBY_FL_USER19’ is not an integer constant expression [-Wpedantic]
 #define RUBY_FL_USER_N(n) RUBY_FL_USER##n = (1<<(RUBY_FL_USHIFT+n))
                                             ^
/usr/include/ruby-2.3.0/ruby/ruby.h:862:5: note: in expansion of macro ‘RUBY_FL_USER_N’
     RUBY_FL_USER_N(19),
     ^~~~~~~~~~~~~~

```

**Comment by take-cheeze** [comment]
Why does ruby build error relate to mruby?

**Comment by letarg0** [comment]
because:
1. mruby meybe have this same trouble
2. i'm not foud issue for ruby

**Comment by fundamental** [comment]
> i'm not foud issue for ruby

It sounds like you're trying to report a CRuby bug to this issue tracker. This issue tracker is for bugs related to MRuby. You can find information on how to report issues to the CRuby bug tracker at https://bugs.ruby-lang.org/projects/ruby/wiki/HowToReport .

> mruby meybe have this same trouble

Just because there's a bug in a CRuby header, does not mean that there is a bug in the MRuby implementation.

**Comment by matz** [comment]
The simple answer is "no".
