### ISSUE TITLE
How to ensure that the GC is not going to clean up my internal variable?

### ISSUE THREAD

**Issue by Moon4u** [mruby/mruby#4114]
I have a native C struct **A** that, when initialized from mruby, creates struct **B**. The struct **B** is accessible by the user from mruby and can be changed. The user can also create a new instance of that structure and assign it to **A**. 
I presume that the problem is that when I create the struct **B** from within the C code, the GC is not quite aware that it's referenced inside **A** and eventually cleanse it. 
What I'm doing is - during the initialization of **A**, I call ````mrb_malloc````, to get memory for **B**. After that, I just pass the **B** instance around. 
I read the [gc arena howto](https://github.com/mruby/mruby/blob/master/doc/guides/gc-arena-howto.md) doc and I tried putting ````mrb_gc_arena_save```` and ````mrb_gc_arena_restore```` around my memory alloc but that didn't change anything. I also tried to use ````mrb_gc_arena_protect```` still no luck. How am I supposed to protect my struct from the GC? Is there anywhere a ref count that I could just increment and decrement when **A** starts/stops using the **B** instance?

**Comment by matz** [comment]
It is difficult to grasp the issue from the above abstract description. Can you show us the code?
The problem might be addressed by write barriers or `mrb_gc_register()` but not sure.

**Comment by Moon4u** [comment]
````c
static struct RClass*	class_B	= NULL;
static struct RClass*	class_A	= NULL;

struct B
{
	unsigned char some_variables[24];
};

struct A
{
	struct B *instance;
	unsigned char some_variables[24];
};

static void free_b(mrb_state *mrb, void *p)
{
	mrb_free(mrb, p);
}

static struct mrb_data_type const b_data_type = { "B", free_b };

struct B* b_get_ptr(mrb_state *mrb, mrb_value value )
{
	void* value_p = mrb_data_get_ptr(mrb, value, &b_data_type);

	return (struct B*) value_p;
}



static void free_a(mrb_state *mrb, void *p)
{
	struct A* a = (struct A*)p;

	if(/* a->intance is not referenced by the user in the ruby code */)
		mrb_free( mrb, a->instance);

	mrb_free(mrb, a);
}

static struct mrb_data_type const a_data_type = { "B", free_a };

struct A* a_get_ptr(mrb_state *mrb, mrb_value value )
{
	void* value_p = mrb_data_get_ptr(mrb, value, &a_data_type);

	return (struct A*) value_p;
}

static mrb_value
a_initialize(mrb_state *mrb, mrb_value self)
{
	struct A* data = (struct A*) DATA_PTR(self);
	if(NULL == data)
	{
		data = (struct A*) mrb_malloc(mrb, sizeof(struct A));

		// The question is about this allocation
		data->instance = (struct B*) mrb_malloc(mrb, sizeof(struct B));
	}

	DATA_PTR(self) = data;
	DATA_TYPE(self) = &a_data_type;

	return self;
}

static mrb_value
get_b_from_a(mrb_state *mrb, mrb_value self)
{
	struct A* a = (struct A*) mrb_data_get_ptr( mrb, self, &a_data_type );
	return mrb_obj_value(Data_Wrap_Struct(mrb, class_B, &b_data_type, a->instance));
}

void mrb_mruby_guard_test_gem_init(mrb_state *mrb)
{
	class_A	= mrb_define_class( mrb, "A", mrb->object_class );
	class_B	= mrb_define_class( mrb, "B", mrb->object_class );

	MRB_SET_INSTANCE_TT(class_A, MRB_TT_DATA);
	MRB_SET_INSTANCE_TT(class_B, MRB_TT_DATA);

	mrb_define_class_method(mrb, class_A, "initialize", a_initialize, 0 );
	mrb_define_class_method(mrb, class_A, "getB", get_b_from_a, 0);
	// There are more methods the classes B and A but they are not 
	// important (mostly getters and setters).
}

void mrb_mruby_guard_test_gem_final(mrb_state *mrb)
{
}
````

I didn't want to post code because it looks too long, but here it is. 
I have not actually tested it, but I hope that it's going to be understandable. I left 2 comments (one in the ```free_a``` function, and one in the  ````a_initialize```` method.

The user code can be something like this:
````ruby
a_inst = A.new
while true
  p "test"
end
````
The print will try to allocate memory, which (I assume) would start the GC and it will clean the B struct inside A. 

I need to know how to tell the GC to leave the allocated B object inside A. Do I add this line do something like this:
````c
mrb_gc_register(mrb, get_b_from_a(mrb, a->instance));
````
I can't test this right now, but I will test it on Monday.

**Comment by dearblue** [comment]
There are two solutions that I came up.

\# Because I am using machine translation by Google, please pardon the disturbance of words.

  - Implement the reference count on its yourself (irrespective of mruby)
  - When creating an instance of A, also create an instance of B and set it as a hidden instance variable of the A instance

## Implement reference count on its yourself (irrespective of mruby)

  - Add a reference count member (eg `size_t refcount;`) to `struct B`.
  - To do `data->instance->refcount = 1;` after doing `data->instance = (struct B *)mrb_malloc(mrb, sizeof(struct B))` in the `a_initialize()` function.
  - To do `a->instance->refcount ++;` when creating instance B in the `get_b_from_a()` function.
  - To do `free_b(a->instance)` in the `free_a()` function.
  - To do `mrb_free(b)` if `b->refcount` is `0` after `b->refcount --;` in the `free_b()` function.

## When creating an instance of A, also create an instance of B and set it as a hidden instance variable of A instance

  - Create an instance of B  in the `a_initialize()` function too.
    `mrb_value obj_b = mrb_obj_value(Data_Wrap_Struct(mrb, class_B, & b_data_type, a->instance));`
    But I think better to use `Data_Make_Struct()` instead of `mrb_malloc()` + `Data_Wrap_Struct()`.
  - Next, add the instance of B as a variable of the instance of A.
    `mrb_iv_set(mrb, obj_a, mrb_intern_lit(mrb, "instance_b"), obj_b);`
    NOTE: Giving a symbol whose instance variable name does not start with `@` will make it invisible from the ruby ​​script.
  - Get and return the instance variable in the `get_b_from_a()` function.
    `return mrb_iv_get(mrb, obj_a, mrb_intern_lit(mrb, "instance_b")))`

You may think that it is sufficient to add and exchange the `mrb_value obj_b;` member to `struct A` without using instance variables, but in that case it is judged to be an object to be destroyed in the mark phase of GC I will.
It is necessary to indicate the relationship between a and b with `mrb_iv_set()` whether or not it is placed on a structure.

**Comment by Moon4u** [comment]
Thank you. This explanation cleared a misunderstanding that I had. I will try to implement this in the following days. 
I will close the issue (at least for now).

**Comment by matz** [comment]
I recommend @dearblue's 2nd approach. This is the official way to protect mruby objects referenced from the other mruby object from GC.
