### ISSUE TITLE
Question regarding usage of cruby gems with mruby

### ISSUE THREAD

**Issue by logicminds** [mruby/mruby#4134]
I have a ruby CLI app that uses several other gems and was wondering how I can convert  to a mruby based binary?  It appears like using common cruby gems is not allowed. 

Can I only use pre existing mgems?  Do I read in all the ruby gem files from the main() method?  Do I just vendor everything into the lib folder?

I am really just looking to create a single binary for my CLI app and thought mruby could help. 

Also, how do I install plugins after my app is installed.  Can mruby load files from the filesystem to extend itself?

Example of cli app: https://github.com/ashrithr/awscli  (not mine)

**Comment by matz** [comment]
I am sorry but C API of CRuby and mruby are totally different. You have to use (or create) mgems implemented for mruby. Since these API are similar, theoretically, it's not impossible to implement a compatibility layer (like JRuby did), but currently, there's no project working on it, as far as I know.

For plugins,  the easiest way is writing your plugin all in Ruby. Or you can implement your own plugin system using mruby-cfunc (or mruby-rubyffi-compat).
