### ISSUE TITLE
How to write core tests depend on mrbgems?

### ISSUE THREAD

**Issue by shuujii** [mruby/mruby#4214]
I'm trying to add tests for #3320 to `test/t/range.rb`. But `Module#remove_method` isn't defined though I enable `mruby-metaprog` mrbgem.

How can I do it?

**Comment by matz** [comment]
The canonical answer for the question is "core test should not depend on mrbgem".
Plus I am not positive about adding regression tests for previous bugs. Because it could drastically increase the number of tests and test execution time. Maybe we can have another set of regression tests but it should be separated from day-to-day tests.

**Comment by shuujii** [comment]
@dearblue and @matz thank you for your reply.

I abandon adding this test this time because it seems that there isn't good place for it now. However tests are necessary for bugs that hard to notice like this, I think.
