### ISSUE TITLE
segfault when accessing instance variables

### ISSUE THREAD

**Issue by tohya-ryu** [mruby/mruby#4617]
I hope this is a trivial problem produced by my lack of knowledge on the GC.

I'm creating a bunch of objects in C via `mrb_obj_new`, later I invoke a method on them via `mrb_funcall`. This works, but after a fixed number of object creations invoking a function and accessing an instance variable (even if only checking for via `puts "#{self.instance_variable_defined?(:@id)}"`) causes a segfault on line 116 in `mruby/src/variable.c`.

The number of objects that can be created before the program segfaults varies on the ruby code - e.g. just putting a bunch of `puts` into the code increases the number of object creations before the crash. 

I'm only saving a reference to the object in a C struct. Could it be this is caused by the GC removing the objects?

**Comment by matz** [comment]
Without seeing the code, there's little to say, but at least you need to protect allocated objects that exported to C/C++ world. Otherwise, objects will be collected and eventually your program will crash. You can use `mrb_gc_register()` to protect exported objects from GC. And  `mrb_gc_unregister()` to stop referencing objects.

**Comment by tohya-ryu** [comment]
Exactly what I was looking for. The functions fixed my issue. Thank you!
