### ISSUE TITLE
codedump.c: OP_LOADINEG is displayed as OP_LOADI

### ISSUE THREAD

**Issue by NaokiM03** [mruby/mruby#5869]
Hi.

```ruby
-42
```

When the above code is compiled with the verbose flag, the following log is displayed.

![image](https://user-images.githubusercontent.com/37442712/206936809-cfe3a5fe-8f41-4feb-aee3-10617eff2ec6.png)

I expected the following.

![image](https://user-images.githubusercontent.com/37442712/206936934-964ef96e-9489-4bcb-a7b5-6eaba53525ed.png)

Is it intended that OP_LOADI is displayed ?

**Comment by NaokiM03** [comment]
Ready to create a pull request.

**Comment by NaokiM03** [comment]
> The `OP_` should be omitted in the display, so it becomes `LOADINEG` instead of `OP_LOADINEG`.

Oh, I'll fix it.

> depends on the person?

Yes, I asked before creating the pull request because I thought it might depend on the person.

**Comment by matz** [comment]
It was intentional.

Since we wanted to save the sign bit for `OP_LOADI`, we separated `OP_LOADI` (positive 0-256 int) and `OP_LOADINEG` (negative -256 to 0). Recent assembler like x86_64 generates different byte sequence from the same instruction, so I thought it was OK to unify `OP_LOADI` and `OP_LOADINEG` in display.

The opinion may vary. If you think displaying exact (and correct) instruction name is crucial and less confusing, I respect your opinion.

**Comment by NaokiM03** [comment]
Understood.

I was confused reading the bytecode, but few users may actually do that. If that is the case, it may be fine as is.
(Maybe if someone else thinks the same thing, they will see this isssue and understand.)

**Comment by matz** [comment]
After consideration, I decided that it's better to disclose `OP_LOADINEG`, where we don't hide `OP_LOADI_1` etc.

**Comment by matz** [comment]
@NaokiM03 To keep your name as a contributor, do you want to submit a pull-request for this issue?

**Comment by NaokiM03** [comment]
@matz 
Created.
https://github.com/mruby/mruby/pull/5870

As you said, considering the current status of `OP_LOADI_x`, I thought it would be better to output the exact OPCODE. Thank you very much.

**Comment by NaokiM03** [comment]
Now that the question has been answered, I will close this isssue. Thank you.
