### ISSUE TITLE
Differentiate between `lib` and `lib64` in the build settings.

### ISSUE THREAD

**Issue by mkoncek** [mruby/mruby#6240]
See: https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/#macros_installation
In Fedora, the default library  path for the `x86_64` architecture is `/usr/lib64`. I would like to be able to export some variable to before the build to allow `rake install` to use that path.

**Comment by dearblue** [comment]
If simply replacing `lib/` directory with `lib64/` during `rake install`, `lib/libmruby.mak` and `bin/mruby-config` will not work.
We need to replace the embedded `lib/` with a variable so that it can be determined at runtime.
And we may also need a mechanism to replace the content of files when they are installed (copied).

If no one else is working on it, I may eventually PR it.

**Comment by rubyFeedback** [comment]
I understand the use case. Personally I still find it wrong to label lib-directories with versions. /usr/lib/ always seemed to make more sense than /usr/lib32/ and /usr/lib64/, but as said, I understand the use case and also agree that build systems should support this. Another awkward thing is versioned binaries, such as /usr/bin/python3.11 or /usr/bin/python3.12. I also understand the use cases here as well (/usr/bin/python is then typically a symlink) but I feel this is all not really an elegant solution.

**Comment by dearblue** [comment]
I have created a PR as #6290.
It can be changed via the `conf.libdir_name` accessor or the `MRUBY_SYSTEM_LIBDIR_NAME` environment variable.
If any comments or questions, please submit them there.
