### ISSUE TITLE
Is possible change this line in gc.h ?

### ISSUE THREAD

**Issue by geek-9** [mruby/mruby#6336]
I embeded mruby in C program
I use:

extern "C" {
#include <mruby.h>
#include <mruby/string.h>
#include <mruby/irep.h>
}

but I get error.

```
In file included from ~/mruby/include/mruby.h:118,
                 from my_funy_super.program.cc:9:
~/mruby/include/mruby/gc.h:51:9: error: ISO C++ forbids flexible array member ‘objects’ [-Wpedantic]
   51 |   void *objects[];
      |         ^~~~~~~

```

**Comment by dearblue** [comment]
That part was fixed in version [3.2.0](https://github.com/mruby/mruby/releases/tag/3.2.0). The current latest version of mruby is [3.3.0](https://github.com/mruby/mruby/releases/tag/3.3.0).
If you need an older version of mruby for some reason, try the patch in commit 24939723d77291152298acc2fb6415b3d1fe2c24.
